CREATE TABLE IF NOT EXISTS Customers
(
    id      INT PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS Teachers
(
    id      INT PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL
);
CREATE TABLE IF NOT EXISTS Students
(
    id      INT PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL
);
CREATE TABLE IF NOT EXISTS Employees
(
    id      INT PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL
);